_BASE_: "../Base-RCNN-FPN-S2.yaml"
MODEL:
  WEIGHTS: "ckp/faster-rcnn-r50-fpn-3x-40.2.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8


#OUTPUT_DIR : "./output/foldername"
