_BASE_: "../Base-RCNN-FPN-S2.yaml"
MODEL:
  WEIGHTS: "ckp/mask-rcnn-r101-fpn-3x-42.9.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

#OUTPUT_DIR : "./output/foldername"